#pragma once
#ifndef __COLORPICKER_HPP
    #define __COLORPICKER_HPP           1
    #define __COLORPICKER_VERSION_MAJOR 0
    #define __COLORPICKER_VERSION_MINOR 0.1
    #define __COLORPICKER_VERSION       ((__COLORPICKER_VERSION_MAJOR + __COLORPICKER_VERSION_MINOR))
#endif
